# ===============================
# APP
# ===============================
spring.application.name=APIRestMain
server.port=8080   
# o 8092 si prefieres

# ===============================
# DATASOURCE (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/db_springboot_dev?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# SQL INIT
# ===============================
spring.sql.init.mode=never

# ===============================
# SWAGGER (SpringDoc)
# ===============================
springdoc.swagger-ui.path=/swagger-ui-custom.html
